# Generated by Django 4.1 on 2022-09-11 07:35

from django.db import migrations, models
import django.db.models.deletion
import utilities.customized_id


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.CharField(default=utilities.customized_id.create_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=utilities.customized_id.create_id, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='undergraduate_app.person')),
                ('specialized_fields', models.ManyToManyField(to='undergraduate_app.field')),
            ],
            bases=('undergraduate_app.person',),
        ),
        migrations.CreateModel(
            name='Collegian',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='undergraduate_app.person')),
                ('study_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undergraduate_app.field')),
            ],
            bases=('undergraduate_app.person',),
        ),
    ]
