# Generated by Django 4.1.1 on 2022-09-24 08:36

from django.db import migrations, models
import django.db.models.deletion
import utilities.customized_id
import utilities.utime


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_app', '0002_role_alter_person_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.PositiveIntegerField(default=utilities.utime.UTime.now)),
                ('description', models.TextField()),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undergraduate_app.professor')),
                ('collegian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undergraduate_app.collegian')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=utilities.customized_id.create_id, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='undergraduate_app.report')),
                ('accepted', models.BooleanField()),
            ],
            bases=('undergraduate_app.report',),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='undergraduate_app.status'),
        ),
    ]
