# Generated by Django 4.1.3 on 2022-11-21 15:00

from django.db import migrations, models
import utilities.customized_id


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_app', '0004_finalproject_weeklyreport_departmenthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.CharField(default=utilities.customized_id.create_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
